### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread-packages/vi#22]
- [ ] 按照原版vi对本仓库进行重校  https://gitee.com/mysterywolf/busybox
- [ ] get_terminal_width_height还需要继续优化一下
- [x] optparse软件包需要同步上游 https://github.com/liu2guang/optparse/pull/5
- [x] remveo ENABLE_FEATURE_VI_USE_SIGNALS

**Comment by mysterywolf** [comment]
```c
#define F_OK    0
#define R_OK    4
#define W_OK    2
#define X_OK    1
```
这一坨应该是rt-thread posix那边该定义的，不应该是vi负责定义的
